### ISSUE TITLE
文章详情页是怎么加入的？

### ISSUE THREAD

**Issue by Cccccl** [xuqiang521/nuxt-ssr-demo#4]
http://118.25.109.133:81/post/5acef004f265da23a2297c71    这样的url 是在服务器上的另外一个服务吗

**Comment by xuqiang521** [comment]
额 ~  这个 ~ 其实真实情况是 ~ 文章详情页目前并没有做，直接通过 nginx 做的代理 指向的掘金线上地址 ~
如果后期有时间的会考虑把剩余的部分完成。当然，如果你能通过 fork 下我这个基础版本然后扩展完成剩余的部分然后给我提 PR 我也是非常欢迎的 ~
