### ISSUE TITLE
本地运行出错

### ISSUE THREAD

**Issue by gongxi036** [xuqiang521/nuxt-ssr-demo#8]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1505:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxt-ssr-demo@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxt-ssr-demo@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-09-21T02_36_22_241Z-debug.log

**Comment by gethin94** [comment]
项目可以在本地运行吗？

**Comment by gethin94** [comment]
> events.js:183
> throw er; // Unhandled 'error' event
> ^
> 
> Error: listen EADDRINUSE 127.0.0.1:3000
> at Object._errnoException (util.js:992:11)
> at _exceptionWithHostPort (util.js:1014:20)
> at Server.setupListenHandle [as _listen2] (net.js:1355:14)
> at listenInCluster (net.js:1396:12)
> at GetAddrInfoReqWrap.doListen [as callback] (net.js:1505:7)
> at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! nuxt-ssr-demo@1.0.0 dev: `nuxt`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the nuxt-ssr-demo@1.0.0 dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2018-09-21T02_36_22_241Z-debug.log
